[package]
name = "InitiaStdlib"
version = "1.0.0"

[dependencies]
MoveStdlib = { local = "../move_stdlib" }
MoveNursery = { local = "../move_nursery" }

[addresses]
std = "0x1"
initia_std = "0x1"
relayer = "0x3d18d54532fc42e567090852db6eb21fa528f952"
